### ISSUE TITLE
Facing a issue in launching DLT-Meta Pipeline through command line

### ISSUE THREAD

**Issue by NehammJain09** [databrickslabs/dlt-meta#18]
Parsing argument complete. args=Namespace(cloud_provider_name='aws', dbr_version='12.2.x-scala2.12', dbfs_path='dbfs:/dais-dlt-meta-demo-automated/')
Traceback (most recent call last):
  File "C:\Users\nehamjain\dlt-meta\dlt-meta-demo\launch_demo.py", line 345, in <module>
    main()
  File "C:\Users\nehamjain\dlt-meta\dlt-meta-demo\launch_demo.py", line 244, in main
    api_client = get_api_client()
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\nehamjain\dlt-meta\dlt-meta-demo\launch_demo.py", line 17, in get_api_client
    api_client = _get_api_client(config, command_name="labs_dlt-meta")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nehamjain\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\databricks_cli\configure\config.py", line 102, in _get_api_client
    verify = config.insecure is None
             ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'insecure'

**Comment by ravi-databricks** [comment]
Looks like you have not setup databricks host and token. For windows user you need to use following:
SET DATABRICKS_HOST=workspace url
SET DATABRICKS_TOKEN=databricks token
make sure you are running on python >3.8

**Comment by NehammJain09** [comment]
@ravi-databricks It helps Thank You!!
