### ISSUE TITLE
Not able to onboard and deploy in interactive python terminal

### ISSUE THREAD

**Issue by mmicikevicius** [databrickslabs/dlt-meta#35]
Hello,

I'm trying to onboard and deploy DLT-META with all the default parameters in terminal, but getting this error:

Traceback (most recent call last):
  File "/Users/mantasmicikevicius/dlt-meta/src/cli.py", line 500, in <module>
    main(*sys.argv[1:])
  File "/Users/mantasmicikevicius/dlt-meta/src/cli.py", line 496, in main
    MAPPING[command](dltmeta)
  File "/Users/mantasmicikevicius/dlt-meta/src/cli.py", line 467, in onboard
    dltmeta.onboard(cmd)
  File "/Users/mantasmicikevicius/dlt-meta/src/cli.py", line 158, in onboard
    self._ws.dbfs.upload(cmd.dbfs_path + f"/dltmeta_conf/{onboarding_filename}", ob_file, overwrite=True)
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/mixins/files.py", line 320, in upload
    with self.open(path, write=True, overwrite=overwrite) as dst:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/mixins/files.py", line 316, in open
    return _DbfsIO(self, path, read=read, write=write, overwrite=overwrite)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/mixins/files.py", line 38, in __init__
    elif write: self._created = api.create(path, overwrite=overwrite)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/service/files.py", line 382, in create
    res = self._api.do('POST', '/api/2.0/dbfs/create', body=body, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/core.py", line 128, in do
    return retryable(self._perform)(method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mantasmicikevicius/dlt-meta/.venv/lib/python3.11/site-packages/databricks/sdk/core.py", line 221, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.ResourceAlreadyExists: A file or directory already exists at the input path dbfs:/dlt-meta_cli_demo/dltmeta_conf/onboarding.json.
Error: exit status 1

**Comment by ravi-databricks** [comment]
@mmicikevicius , did you follow steps given [here](https://github.com/databrickslabs/dlt-meta?tab=readme-ov-file#databricks-labs-dlt-meta-cli-lets-you-run-onboard-and-deploy-in-interactive-python-terminal)?
Above error says onboarding file already exists, Can you details about options to onboard cli?
